// Logo.dev helper — uses public publishable token only
const LOGO_DEV_PUBLISHABLE_TOKEN = "pk_aR1b148PRMSUsm7Sptau1g";

/**
 * Generate a logo.dev image URL for a given domain.
 * @param domain e.g. "stripe.com" — do NOT include protocol
 * @param options.retina 2x resolution
 * @param options.size image size in px
 */
export function getLogoUrl(
  domain: string | undefined,
  options?: { retina?: boolean; size?: number; greyscale?: boolean }
): string | undefined {
  if (!domain) return undefined;
  const cleanDomain = domain.replace(/^https?:\/\//, "").replace(/\/+$/, "");
  if (!cleanDomain) return undefined;

  const params = new URLSearchParams();
  params.set("token", LOGO_DEV_PUBLISHABLE_TOKEN);
  if (options?.retina) params.set("retina", "true");
  if (options?.greyscale) params.set("greyscale", "true");
  if (options?.size) params.set("size", String(options.size));

  return `https://img.logo.dev/${cleanDomain}?${params.toString()}`;
}

/** Known domain mapping for major partners (add more as needed) */
export const partnerDomainMap: Record<string, string> = {
  // Government / EU / UN
  "Board for Certification of Genealogists": "bcgcertification.org",
  "U.S. Department of Commerce": "commerce.gov",
  "Australian Government": "australia.gov.au",
  "Eureka Network": "eurekanetwork.org",
  "European Commission": "ec.europa.eu",
  "Council of the European Union": "consilium.europa.eu",
  "UNCTAD": "unctad.org",
  "WTO": "wto.org",
  "WHO": "who.int",
  "Digitale Verwaltung Schweiz": "bit.admin.ch",
  "UN-Habitat": "unhabitat.org",
  "UNEP": "unep.org",
  "UN Global Compact Germany": "unglobalcompact.org",
  "Deutscher Bundestag": "bundestag.de",
  "UNICEF (HQ)": "unicef.org",
  "UN Global Compact": "unglobalcompact.org",
  "UNESCO": "unesco.org",
  "European Banking Authority": "eba.europa.eu",
  "CTBTO": "ctbto.org",
  "EUIPO": "euipo.europa.eu",
  "FICPI": "ficpi.org",
  "Consejo General de la Abogacía": "abogacia.es",
  "European Patent Office": "epo.org",
  "European Investment Fund": "eif.org",
  "St. Patrick's Festival": "stpatricksfestival.ie",
  "Basilica of National Shrine": "nationalshrine.org",
  "European Parliament": "europarl.europa.eu",
  "WIPO": "wipo.int",
  "USPTO": "uspto.gov",
  "FINRA": "finra.org",
  "NATO": "nato.int",
  "OECD": "oecd.org",
  "Interpol": "interpol.int",
  "Red Cross": "redcross.org",
  "World Bank": "worldbank.org",
  "IMF": "imf.org",
  "OPEC": "opec.org",
  "ASEAN": "asean.org",
  "African Union": "au.int",
  "G7": "g7germany.de",
  "G20": "g20.org",
  "World Economic Forum": "weforum.org",

  // Tech / Corporate
  "Madison Square Garden Ent.": "msg.com",
  "IBM Corporation": "ibm.com",
  "Google": "google.com",
  "Auth0": "auth0.com",
  "Arm Ltd": "arm.com",
  "OpenSSF": "openssf.org",
  "Linux Foundation": "linuxfoundation.org",
  "GitHub": "github.com",
  "AWS": "aws.amazon.com",
  "Microsoft": "microsoft.com",
  "Intel": "intel.com",
  "NSF": "nsf.gov",
  "I-Corps Hub": "nsf.gov",
  "Frontegg": "frontegg.com",
  "OpenAI": "openai.com",
  "500 Global": "500.co",
  "Microsoft for Startups": "microsoft.com",
  "AWS Activate": "aws.amazon.com",
  "Shell": "shell.com",
  "Siemens": "siemens.com",
  "Bosch": "bosch.com",
  "SAP": "sap.com",
  "Airbus": "airbus.com",
  "Bayer": "bayer.com",
  "BASF": "basf.com",
  "Allianz": "allianz.com",
  "Deutsche Bank": "db.com",
  "Lufthansa": "lufthansa.com",
  "Adidas": "adidas.com",
  "Puma": "puma.com",
  "Spotify": "spotify.com",
  "Samsung": "samsung.com",
  "Sony": "sony.com",
  "Ericsson": "ericsson.com",
  "Nokia": "nokia.com",

  // Personal Projects / HNOSS Network
  "StatesFlowWishes": "statesflowwishes.eu",
  "ValueSky": "valuesky.biz",
  "Heftling": "heftling.de",
  "sTarLighTsMoveMenTs": "statesflowwishes.eu",
  "ChurchPattern": "heftling.de",
  "GardienSystem": "heftling.de",
  "Moonschlee": "heftling.de",
  "pFihPeAcuST": "github.com",
  "Pathwinding": "heftling.de",
  "Phmegtishen": "statesflowwishes.eu",
  "Flykniwnie": "statesflowwishes.eu",
  "dfffoesssooooassso": "epo.org",

  // New Fortune 500 / Big Tech
  "Apple": "apple.com",
  "NVIDIA": "nvidia.com",
  "Tesla": "tesla.com",
  "Meta": "meta.com",
  "Alphabet": "abc.xyz",
  "Amazon": "amazon.com",
  "Oracle": "oracle.com",
  "Salesforce": "salesforce.com",
  "Adobe": "adobe.com",
  "Netflix": "netflix.com",
  "PayPal": "paypal.com",
  "Uber": "uber.com",
  "Airbnb": "airbnb.com",
  "LinkedIn": "linkedin.com",
  "Zoom": "zoom.us",
  "Shopify": "shopify.com",
  "Stripe": "stripe.com",
  "Coinbase": "coinbase.com",
  "Cloudflare": "cloudflare.com",
  "Datadog": "datadoghq.com",
  "Atlassian": "atlassian.com",
  "Wise": "wise.com",
  "Monzo": "monzo.com",
  "Figma": "figma.com",
  "Vercel": "vercel.com",

  // New EU Institutions
  "European Central Bank": "ecb.europa.eu",
  "European Court of Justice": "curia.europa.eu",
  "European Court of Auditors": "eca.europa.eu",
  "European External Action Service": "eeas.europa.eu",
  "European Defence Agency": "eda.europa.eu",
  "Frontex": "frontex.europa.eu",
  "Europol": "europol.europa.eu",
  "Eurojust": "eurojust.europa.eu",
  "European Space Agency": "esa.int",
  "CERN": "home.cern",
  "European Investment Bank": "eib.org",
  "European Stability Mechanism": "esm.europa.eu",
  "EU Agency for Cybersecurity": "enisa.europa.eu",
  "European Medicines Agency": "ema.europa.eu",
  "European Aviation Safety Agency": "easa.europa.eu",

  // New UN Agencies
  "UNDP": "undp.org",
  "UNHCR": "unhcr.org",
  "WFP": "wfp.org",
  "ILO": "ilo.org",
  "FAO": "fao.org",
  "UNIDO": "unido.org",
  "ITU": "itu.int",
  "IMO": "imo.org",
  "ICAO": "icao.int",
  "UNFPA": "unfpa.org",
  "UNOPS": "unops.org",
  "UN Women": "unwomen.org",
  "IAEA": "iaea.org",
  "OPCW": "opcw.org",
  "UNODC": "unodc.org",
  "OHCHR": "ohchr.org",

  // NGOs
  "Amnesty International": "amnesty.org",
  "Greenpeace": "greenpeace.org",
  "Doctors Without Borders": "msf.org",
  "Oxfam": "oxfam.org",
  "Save the Children": "savethechildren.org",
  "World Wildlife Fund": "wwf.org",
  "Transparency International": "transparency.org",
  "Human Rights Watch": "hrw.org",
  "CARE International": "care.org",
  "International Rescue Committee": "rescue.org",

  // Automotive / Luxury
  "Toyota": "toyota.com",
  "Volkswagen Group": "volkswagen.com",
  "Mercedes-Benz Group": "mercedes-benz.com",
  "BMW Group": "bmwgroup.com",
  "Honda": "honda.com",
  "Hyundai": "hyundai.com",
  "General Motors": "gm.com",
  "Ford Motor": "ford.com",
  "Stellantis": "stellantis.com",
  "Ferrari": "ferrari.com",
  "Porsche": "porsche.com",
  "Audi": "audi.com",
  "Volvo": "volvocars.com",
  "Jaguar Land Rover": "jaguarlandrover.com",
  "Aston Martin": "astonmartin.com",
  "McLaren": "mclaren.com",
  "Rolls-Royce Motor Cars": "rolls-roycemotorcars.com",
  "Bentley": "bentleymotors.com",

  // Finance
  "JPMorgan Chase": "jpmorganchase.com",
  "Bank of America": "bankofamerica.com",
  "Citigroup": "citi.com",
  "Goldman Sachs": "goldmansachs.com",
  "Morgan Stanley": "morganstanley.com",
  "Wells Fargo": "wellsfargo.com",
  "HSBC": "hsbc.com",
  "Barclays": "barclays.com",
  "Standard Chartered": "sc.com",
  "UBS": "ubs.com",
  "Credit Suisse": "credit-suisse.com",
  "BNP Paribas": "bnpparibas.com",
  "Société Générale": "socgen.com",
  "Crédit Agricole": "credit-agricole.com",
  "ING Group": "ing.com",

  // Energy
  "ExxonMobil": "exxonmobil.com",
  "Chevron": "chevron.com",
  "BP": "bp.com",
  "TotalEnergies": "totalenergies.com",
  "Equinor": "equinor.com",
  "Eni": "eni.com",
  "Saudi Aramco": "aramco.com",
  "Petrobras": "petrobras.com.br",
  "Schlumberger": "slb.com",
  "Halliburton": "halliburton.com",

  // Pharma
  "Johnson & Johnson": "jnj.com",
  "Pfizer": "pfizer.com",
  "Roche": "roche.com",
  "Novartis": "novartis.com",
  "Merck": "merckgroup.com",
  "Sanofi": "sanofi.com",
  "AstraZeneca": "astrazeneca.com",
  "GlaxoSmithKline": "gsk.com",
  "Eli Lilly": "lilly.com",
  "AbbVie": "abbvie.com",
  "Medtronic": "medtronic.com",
  "Philips Healthcare": "philips.com",
  "Siemens Healthineers": "siemens-healthineers.com",

  // Telecom
  "Verizon": "verizon.com",
  "AT&T": "att.com",
  "T-Mobile": "t-mobile.com",
  "China Mobile": "chinamobileltd.com",
  "Deutsche Telekom": "telekom.com",
  "Telefónica": "telefonica.com",
  "Orange": "orange.com",
  "Vodafone": "vodafone.com",
  "Telstra": "telstra.com.au",
  "Singtel": "singtel.com",

  // Aerospace / Defence
  "Lockheed Martin": "lockheedmartin.com",
  "Boeing": "boeing.com",
  "Raytheon": "rtx.com",
  "Northrop Grumman": "northropgrumman.com",
  "General Dynamics": "gd.com",
  "BAE Systems": "baesystems.com",
  "Thales": "thalesgroup.com",
  "Safran": "safran-group.com",
  "Leonardo": "leonardocompany.com",
  "Dassault Aviation": "dassault-aviation.com",

  // Consulting
  "McKinsey": "mckinsey.com",
  "Boston Consulting Group": "bcg.com",
  "Bain & Company": "bain.com",
  "Accenture": "accenture.com",
  "Deloitte": "deloitte.com",
  "PwC": "pwc.com",
  "EY": "ey.com",
  "KPMG": "kpmg.com",
  "Capgemini": "capgemini.com",
  "Infosys": "infosys.com",
  "TCS": "tcs.com",
  "Wipro": "wipro.com",

  // Governments
  "UK Government": "gov.uk",
  "French Government": "gouvernement.fr",
  "Canadian Government": "canada.ca",
  "Japanese Government": "japan.go.jp",
  "Chinese Government": "gov.cn",
  "Indian Government": "india.gov.in",
  "Brazilian Government": "gov.br",
  "South African Government": "gov.za",
  "Swiss Government": "admin.ch",
  "Dutch Government": "government.nl",
  "Singapore Government": "gov.sg",
  "Swedish Government": "sweden.se",
  "Norwegian Government": "regjeringen.no",
  "Danish Government": "denmark.dk",
  "Finnish Government": "finland.fi",
  "Austrian Government": "austria.info",
  "Belgian Government": "belgium.be",
  "Spanish Government": "lamoncloa.gob.es",
  "Italian Government": "governo.it",
  "Portuguese Government": "portugal.gov.pt",
  "Greek Government": "gov.gr",
  "Polish Government": "gov.pl",
  "Czech Government": "vlada.cz",
  "Hungarian Government": "kormany.hu",
  "Turkish Government": "tccb.gov.tr",
  "South Korean Government": "korea.net",
  "Taiwan Government": "taiwan.gov.tw",
  "Thai Government": "thailand.go.th",
  "Indonesian Government": "indonesia.go.id",
  "Mexican Government": "gob.mx",
  "Argentine Government": "argentina.gob.ar",
  "Egyptian Government": "egypt.gov.eg",
  "Israeli Government": "gov.il",
  "UAE Government": "u.ae",

  // Additional Tech
  "Cisco": "cisco.com",
  "Dell Technologies": "dell.com",
  "HP": "hp.com",
  "Lenovo": "lenovo.com",
  "AMD": "amd.com",
  "Qualcomm": "qualcomm.com",
  "Broadcom": "broadcom.com",
  "Micron": "micron.com",
  "TSMC": "tsmc.com",
  "ASML": "asml.com",
  "Infineon": "infineon.com",
  "NXP": "nxp.com",
  "STMicroelectronics": "st.com",
  "Renesas": "renesas.com",
  "MediaTek": "mediatek.com",
  "Grab": "grab.com",
  "GoTo Group": "gotocompany.com",
  "Sea Limited": "seagroup.com",
  "Rakuten": "rakuten.com",
  "SoftBank": "softbank.jp",
  "Panasonic": "panasonic.com",
  "Hitachi": "hitachi.com",
  "Siemens Energy": "siemens-energy.com",
  "ABB": "abb.com",
  "Schneider Electric": "se.com",
  "Danfoss": "danfoss.com",
};
